apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  config: |
    executorImage: docker.io/julienbalestra/argoexec:latest
    containerRuntimeExecutor: kubelet
